version: '3.8'

services:
  backend:
    build: ./backend
    container_name: sockstore-backend
    restart: unless-stopped
    volumes:
      - "./backend/socks.json:/app/socks.json"
    expose:
      - "5000"
    networks:
      - sockstore-network

  frontend:
    build: ./nginx
    container_name: sockstore-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - "./frontend:/usr/share/nginx/html"
      - "./static:/usr/share/nginx/html/static"
    networks:
      - sockstore-network

networks:
  sockstore-network:
    driver: bridge